重复: "§2请再摆放一次确保你记住了你摆放的物品哦！"
分割线: "§d我只是一个可爱的分割线啦！"
登入: "§d按照你上次摆放的样子摆放我就知道你还是之前那个可爱的你啦！"
注册: "§ehi你好啊，第一次来吧！点击你喜欢的物品吧！要记住哦。"
确定: "§2我摆好了！"
取消: "§d我要重新摆！"
登入时旁观者模式: true
服务器游戏模式: "SURVIVAL"
声音: true
密码错误: "§d你摆放的方式和以前不同了，我不喜欢你了！"
两次密码不一致: "§e哈哈，你好像记错了。"
登入成功1: "欢迎回来 %玩家%"
登入成功2: "我想死你了 %玩家%"
登入成功后台执行命令: "reg %玩家%66666"
注册成功1: "欢迎大佬入住本服务器"
注册成功2: "§d%玩家% 你这么可爱，应该是个大佬吧！"
注册成功后台执行命令: "reg %玩家%66666"
登入超时踢出玩家: true
登入超时时间: 120
登入超时踢出玩家提示消息: "你为什么不登入啊，一直不登入我生气了，哼！"
修改密码箱子标题: "§e你要修改密码吗？先输入一次你的密码，让我知道是不是有坏人想盗你号！"
取消修改密码1: "你取消了修改密码"
取消修改密码2: "你不修改密码干嘛麻烦我！"
输入你想修改的密码: "§a输入你想修改的密码吧！"

#如果客户端拾取物品后不显示，可开去此选项，否则不必开启。
拾取物品GUG后客户端不显示修复: false
#毫秒，1秒等于1000毫秒，只有玩家移动时刷新，这是背包最大刷新数度。
拾取物品GUG背包刷新速度: 250

分割线物品: "PINK_STAINED_GLASS_PANE"
确定按钮物品: "RED_STAINED_GLASS_PANE"
重新输入按钮物品: "LIME_STAINED_GLASS_PANE"
选择物品:
  - "BONE"
  - "SUGAR"
  - "BELL"
  - "LANTERN"
  - "CAMPFIRE"
  - "SOUL_CAMPFIRE"
  - "WHITE_BED"
  - "PLAYER_HEAD"
  - "CAMPFIRE"
  - "TRAPPED_CHEST"
  - "LECTERN"
  - "ELYTRA"
  - "DARK_OAK_BOAT"
  - "SADDLE"
  - "DIAMOND"
  - "IRON_INGOT"
  - "EMERALD"
  - "GOLD_INGOT"
  - "PAPER"
  - "BLAZE_ROD"
  - "SHULKER_SHELL"
  - "BRICK"
  - "BEACON"
  - "CONDUIT"
  - "SCUTE"
  - "WHEAT"
  - "NETHER_STAR"
  - "NETHER_WART"
  - "ARROW"
  - "BOW"
  - "DIAMOND_SWORD"
  - "DIAMOND_CHESTPLATE"
  - "CHAINMAIL_HELMET"
  - "GOLDEN_LEGGINGS"
  - "TRIDENT"
  - "CROSSBOW"
#名字填""表示不设置
名字:
  - "我是一个小骨头"
  - ""
  - ""
  - ""
  - ""
  - ""
  - ""
  - ""
  - ""
  - ""
  - ""
  - ""
  - ""
  - ""
  - ""
  - ""
  - ""
  - ""
  - ""
  - ""
  - ""
  - ""
  - ""
  - ""
  - ""
  - ""
  - ""
  - ""
  - ""
  - ""
  - ""
  - ""
  - ""
  - ""
  - "我是一个三叉积"
  - ""
lore:
  -
    - "我是只是一个小骨头"
    - "不要点我"
  -
    - "啦啦啦，选我"
  -
    - "别选他"
  -
    - "呜呜呜，没人要我"
  -
  -
  -
  -
  -
  -
    - "上面的都是垃圾"
  -
    - "我左边的才是垃圾"
  -
  -
  -
  -
  -
  -
  -
  -
  -
    - "看不见我，看不见我"
  -
  -
  -
  -
  -
  -
    - "选我"
  -
    - "选他"
  -
    - "吃瓜"
  -
  -
  -
  -
  -
  -
  -
  -
    - "我是最后一个"
    - "heheh"